name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository dengan dukungan Git LFS
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true # <-- WAJIB: Mendownload file LFS yang sebenarnya

    # 2. Setup JDK / Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3. Setup Gradle Cache & Permissions
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Make gradlew executable
      run: chmod +x gradlew

    # 4. Build APK
    - name: Build with Gradle
      run: ./gradlew assembleDebug
